import Head from 'next/head'
import styles from '../styles/Home.module.css'
import App from './App'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ToDO App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Col span={22} offset={10}> */}
        {/* <h1>My To-Do-List
           <PandaIcon
            style={{
              fontSize: '35px',
            }}
          /> 
        </h1> */}
      {/* </Col> */}
      <App /> 
      
    </div>
  )
}